SERIALIZATION_TYPE_NONE = 0
SERIALIZATION_TYPE_EOF = 1
SERIALIZATION_TYPE_CHAR = 2
SERIALIZATION_TYPE_SHORT = 3
SERIALIZATION_TYPE_INT = 4
SERIALIZATION_TYPE_LONG = 5
SERIALIZATION_TYPE_FLOAT = 6
SERIALIZATION_TYPE_DOUBLE = 7
SERIALIZATION_TYPE_BLOB = 8

SIZE_BYTE = 0
SIZE_2BYTES = 1
SIZE_4BYTES = 2
SIZE_8BYTES = 3
SERIALIZER_TRUE = 1
SERIALIZER_FALSE = 0